### ISSUE TITLE
hightlights turning pink in single image mode

### ISSUE THREAD

**Issue by ultra-sonic** [wjakob/hdrmerge#3]
Hi Wenzel,

i am playing around with hdrmerge using just a single image to check if can gain some dynamic range out of my raw-images. 

Unfortunately all hightlights turn pink. Do you have an idea what i did wrong? 

I triple checked my --sensor2xyz matrix and I need to say that the rest of the image (values<1.0) is looking correct.

any ideas?

**Comment by wjakob** [comment]
Hi Oliver,

I had similar issues when dealing with saturated colors that the camera could pick up, but which were out of the sRGB gamut (i.e. I got negative values which were then clipped, causing color inconsistencies).

If that is the case, then the right solution for this would be to store XYZ images followed by some kind of color mapping (LittleCMS is a good library for doing that)  -- however, you'll have to modify the code or write a separate small program to do that.

Wenzel

**Comment by KelSolaar** [comment]
What you see is because some of your data has saturated the sensor. As the tool is meant to produce HDRI images, I'm fairly sure Wenzel didn't implemented any highlight recovery.

Theoretically you wouldn't need it anyway because in the case of HDRI, you are meant to capture the whole dynamic range of a scene through multiple exposures and avoid reaching sensor saturation when all the exposures are combined.

However if developing a single image where you have saturated the sensor (clipped values in one or more channels) then you need to perform highlights recovery.

**Comment by wjakob** [comment]
.. right -- that's another possibility: if your image has pixels that are over-exposed in all images, then the job of hdrmerge is not really well-defined. You'll need a highlight recovery algorithm that considers the neighborhood as well.

**Comment by KelSolaar** [comment]
The magenta tint is typical has sensors *usually* saturate blue channel first, then green and red last.

*dcrwaw* implements various strategy for highlight recovery, some of them can be mimicked in Nuke. I don't have the code front of me atm, so I don't remember which one.

**Comment by ultra-sonic** [comment]
Hey Wenzel and Thomas,

thx for these information, which make total sense! But I don't think I'm going implement highlight recovery ;)

I just wanted to see if one could gain a little more dynamic range from a single CR2...

cheers
Oliver

**Comment by wjakob** [comment]
The dynamic range is already in the CR2 :) -- hdrmerge just gives you a way of converting it into a more usable file format.

I'll close this ticket then.

Best,
Wenzel

**Comment by ultra-sonic** [comment]
@KelSolaar: I guess highlight recovery will never give me back the correct highlights as if I had an hdr sequence,right?

**Comment by KelSolaar** [comment]
Unfortunately no! *Cheap* approaches like within dcraw / ACR will just neutralise them, ensuring that your whites stay whites. There are better algorithm though: http://www.cs.ubc.ca/~heidrich/Papers/PROCAMS.12.pdf but it is quite involving.
