### ISSUE TITLE
Successful build on Windows?

### ISSUE THREAD

**Issue by caron** [wjakob/hdrmerge#4]
Has this project ever been built on Windows?

**Comment by wjakob** [comment]
Not that I know -- PRs to fix build issues are welcomed.

**Comment by caron** [comment]
this branch in my fork is working...

https://github.com/caron/hdrmerge/tree/windows-fixes

this isn't ready to be merged back because i opted to change some code to work only for windows so i could just get it working. the program works but i need to figure out all the settings, my first stab produces something unexpected

**Comment by wjakob** [comment]
Hi Steve,

this looks great! Would you be willing to #ifdef your Windows-specific changes and submit a PR?

Thanks,
Wenzel

**Comment by caron** [comment]
yes, i am willing to do so, but i have a bit more work to do on it first... i will get a PR sometime this week.

**Comment by wjakob** [comment]
Apologies for the delay -- this is all merged now.

**Comment by caron** [comment]
Great! I see your OSX fixes committed and will pull those and make sure Windows is still working.
