### ISSUE TITLE
exr files aren't loading

### ISSUE THREAD

**Issue by caron** [wjakob/hdrmerge#5]
Hello Wenzel,

I have successfully compiled hdrmerge on Windows and the program seems to complete correctly but the resulting exr files don't load into Nuke or Photoshop. Nuke complains about the bounding box not being set. Oddly enough they load into Softimage's compositor, which isn't really useful. They also seem to load into all of the OpenEXR apps (exrheader, exrmaketiled, etc) but all of their output also fails to load into Nuke.

I am using OpenEXR 2.2, could this be a problem?

`c:\dev_local\hdrmerge-build-vs2013>hdrmerge --config hdrmerge_canon_5d.cfg --output hdrmerge_test_1.exr IMG_0028.CR2 IMG_0029.CR2 IMG_0030.CR2
Found 3 images [ISO 500, f/10, exposures times: 1/332, 1/41.5, 1/5.187]
Collected 219 metadata entries.
Loading raw image data ..... done (5634x3753, using 120.989 MiB of memory)
Merging 3 exposures ..
AHD demosaicing ..
Transforming to sRGB color space ..
Writing hdrmerge_test_1.exr (5634x3753, 3 channels, half precision) ..`

**Comment by caron** [comment]
I am using an older version of Nuke, so it doesn't support the new format and I think it is specifically due to the attributes and layer names longer than 31 characters. If I don't write the metadata from the camera to the exr it works...

So I have it commented out now but I will add a flag to skip metadata (which I have doing) or do something ugly like truncate names longer than 31 and expose it as a 'compatibility' flag

**Comment by wjakob** [comment]
Ah, I hate that incompatibility -- this has caused so much confusion in the past.
