### ISSUE TITLE
Remove chromatic abberation

### ISSUE THREAD

**Issue by caron** [wjakob/hdrmerge#8]
I am getting good results from hdrmerge but near edges of the image and edges of objects, especially bright objects, there is chromatic aberration. I don't know what the standard method for removing chromatic aberration is but I would be interested in adding it myself. Any pointers to existing methods (code or literature) for removing chromatic aberration?

**Comment by wjakob** [comment]
This is really more of a post-processing issue (I presume those abberations would be part of all HDR exposures). You could take a look at what darktable does, they have pretty good implementations of filters etc.
